// Generates :core:icons glyph VectorDrawables and the package -> glyph map
// from design/icons. Run: node tools/build-icons.mjs
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { ROOT, loadGlyphs, loadPackages, resName, toPathData } from './glyph-source.mjs';

const RES = `${ROOT}core/icons/src/main/res/drawable`;
const KT = `${ROOT}core/icons/src/main/java/com/sabertheme/core/icons/GeneratedGlyphs.kt`;
const HEADER = 'Generated by tools/build-icons.mjs from design/icons. Do not edit.';

const { APPS, UI } = loadGlyphs();
const packages = loadPackages();

for (const key of Object.keys(packages)) {
  if (!APPS[key]) throw new Error(`packages.json: unknown glyph "${key}"`);
}

function vector(paths) {
  const body = paths.map(d => `    <path
        android:pathData="${d}"
        android:strokeColor="#FFFFFFFF"
        android:strokeWidth="1.75"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />`).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${HEADER} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
${body}
</vector>
`;
}

mkdirSync(RES, { recursive: true });
for (const f of readdirSync(RES)) if (f.startsWith('glyph_')) rmSync(`${RES}/${f}`);

const all = [
  ...Object.entries(APPS).map(([k, [, svg]]) => [k, svg]),
  ...Object.entries(UI),
];
for (const [key, svg] of all) {
  writeFileSync(`${RES}/glyph_${resName(key)}.xml`, vector(toPathData(svg)));
}

const q = s => JSON.stringify(s);
const kt = `// ${HEADER}
package com.sabertheme.core.icons

/** App glyphs, keyed as in design/icons/glyphs.js. */
enum class AppGlyph(val key: String, val label: String, val drawable: Int) {
${Object.entries(APPS).map(([k, [label]]) => `    ${resName(k).toUpperCase()}(${q(k)}, ${q(label)}, R.drawable.glyph_${resName(k)}),`).join('\n')}
}

/** UI glyphs used by launcher chrome and widgets. */
enum class UiGlyph(val drawable: Int) {
${Object.keys(UI).map(k => `    ${resName(k).replace(/^ui_/, '').toUpperCase()}(R.drawable.glyph_${resName(k)}),`).join('\n')}
}

/** Package name -> glyph, from design/icons/packages.json. */
internal val PACKAGE_GLYPHS: Map<String, AppGlyph> = mapOf(
${Object.entries(packages).flatMap(([k, pkgs]) => pkgs.map(p => `    ${q(p)} to AppGlyph.${resName(k).toUpperCase()},`)).join('\n')}
)
`;
writeFileSync(KT, kt);
console.log(`icons: ${Object.keys(APPS).length} app + ${Object.keys(UI).length} ui glyphs, ${Object.values(packages).flat().length} package mappings`);
