// Builds the Figma plugin: design/icons/glyphs.js + design/figma-plugin/src/code.js
// -> design/figma-plugin/dist/code.js. Run: node tools/build-plugin.mjs
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { GLYPHS_JS, ROOT } from './glyph-source.mjs';

const PLUGIN = `${ROOT}design/figma-plugin`;
const out = [
  '// Generated by tools/build-plugin.mjs. Edit design/figma-plugin/src/code.js',
  '// and design/icons/glyphs.js instead.',
  '',
  readFileSync(GLYPHS_JS, 'utf8'),
  readFileSync(`${PLUGIN}/src/code.js`, 'utf8'),
].join('\n');

mkdirSync(`${PLUGIN}/dist`, { recursive: true });
writeFileSync(`${PLUGIN}/dist/code.js`, out);
console.log(`plugin: dist/code.js (${out.length} chars)`);
